#!/bin/sh

#无限循环
while true;
do


	#获取mac与信号衰减
	maclist=(`iw dev wlanz station dump | grep "Station" | cut -f 2 -s -d " "`)
	rxlist=(`iw dev wlanz station dump | grep "signal:" | cut -f 3 -s -d " "`)
	#maclist=(`iwinfo wlanz assoclist | grep "dBm" | cut -f 1 -s -d " "`)
	#rxlist=(`iwinfo wlanz assoclist | grep "dBm" | cut -f 3 -s -d " "`)
	#获取设定参考值
	consult=(`uci -q get wireless.default_radioz.weak`)
	strong=(`uci -q get wireless.default_radioz.strong`)
	#获取系统时间
	time=(`date +%f`)
	#这个不知道应该是控制输出
	len=${#maclist[@]}
	for((i=0;i<$len;i++))
	do

		mac=${maclist[$i]}
		rx=${rxlist[$i]}

		#防止无配置时乱踢
		((a=$consult+0))
		((b=$strong+0))

#--------------------------负数反转--------------------------

		#负数转正数 弱信号
		((c=100$a))
		((d=100-$c))

		#负数转正数 强信号
		((e=100$b))
		((f=100-$e))

		#负数转正数 动态信号
		((g=100$rx))
		((h=100-$g))

#--------------------------单双判断--------------------------

		#判断单双数 弱信号
		I=(`echo "$d" | grep '$' | wc -L`)

		#判断单双数 强信号
		j=(`echo "$f" | grep '$' | wc -L`)

		#判断单双数 动态信号
		k=(`echo "$h" | grep '$' | wc -L`)

#--------------------------单双对比--------------------------

		#单数对比 弱信号
		if [[ "1" = "$k" ]]; then
		if [[ "$I" = "1" ]]; then
		if [[ "$d" < "$h" ]]; then
		o=1
		else
		o=0
fi
fi
		#单数对比 强信号
		if [[ "$j" = "1" ]]; then
		if [[ "$f" > "$h" ]]; then
		p=1
		else
		p=0
fi
fi
		else
		#双数对比 弱信号
		if [[ "$I" < "$k" ]]; then
		o=1
		else
		if [[ "$I" = "$k" ]]; then
		if [[ "$d" < "$h" ]]; then
		o=1
		else
		o=0

fi
fi
fi

		#双数对比 强信号
		if [[ "$j" > "$k" ]]; then
		p=1
		else
		if [[ "$j" = "$k" ]]; then
		if [[ "$f" > "$h" ]]; then
		p=1
		else
		p=0

fi
fi
fi
fi


		#信号强度比较 弱信号剔除
		if [[ "$o" = "1" ]]; then
		#端茶送客，人走茶凉！有朋自远方来 吾之送走乎 闭门谢客叁秒 承蒙再临叨扰
		ubus call hostapd.wlanz del_client '{"addr":"'"$mac"'", "reason": 5, "deauth": True, "ban_time": 3000}'
		echo "[ 弱信号 ]$time 启禀主人：wlanz|$mac $rx已经被撵走了呢，么么哒！" >> /var/log/kickass.log

		fi

		#阀值比较 中立不作操作
		if [[ "$consult" = "$strong" ]]; then
		q=0
		else
		#无配置不工作
		if [[ "$b" = "0" ]]; then
		q=0
		else
		q=$p
		fi

		#信号强度比较 强信号剔除
		if [[ "$q" = "1" ]]; then
		#端茶送客，人走茶凉！有朋自远方来 吾之送走乎 闭门谢客叁秒 承蒙再临叨扰
		ubus call hostapd.wlanz del_client '{"addr":"'"$mac"'", "reason": 5, "deauth": True, "ban_time": 3000}'
		echo "[ 强信号 ]$time 启禀主人：wlanz|$mac $rx已经被赶跑了呢，么么哒！" >> /var/log/kickass.log

		fi
		fi
	done

	#延时0秒
	sleep 0

	#中断循环
	break;

done
