#!/bin/sh

#无限循环
while true;
do


	#获取mac与信号衰减
	maclist=(`iw dev wlanz station dump | grep "Station" | cut -f 2 -s -d " "`)
	rxlist=(`iw dev wlanz station dump | grep "signal:" | cut -f 3 -s -d " "`)
	#maclist=(`iwinfo wlanz assoclist | grep "dBm" | cut -f 1 -s -d " "`)
	#rxlist=(`iwinfo wlanz assoclist | grep "dBm" | cut -f 3 -s -d " "`)
	#获取设定参考值
	consult=(`uci -q get wireless.default_radioz.weak`)
	strong=(`uci -q get wireless.default_radioz.strong`)
	#获取系统时间
	time=(`date +%f`)
	#这个不知道应该是控制输出
	len=${#maclist[@]}
	for((i=0;i<$len;i++))
	do

		mac=${maclist[$i]}
		rx=${rxlist[$i]}

		#防止无配置时乱踢
		((aaa=$consult+0))
		((bbb=$strong+0))

		#负数转正数 弱信号
		((ccc=100$aaa))
		((ddd=100-$ccc))

		#弱信号滑动输出
		if [[ "$ddd" = "9" ]]; then
		ab=8
		else
		if [[ "$ddd" = "8" ]]; then
		ab=7
		else
		if [[ "$ddd" = "7" ]]; then
		ab=6
		else
		if [[ "$ddd" = "6" ]]; then
		ab=5
		else
		if [[ "$ddd" = "5" ]]; then
		ab=4
		else
		if [[ "$ddd" = "4" ]]; then
		ab=3
		else
		if [[ "$ddd" = "3" ]]; then
		ab=2
		else
		if [[ "$ddd" = "2" ]]; then
		ab=1
		else
		if [[ "$ddd" = "1" ]]; then
		ab=0
		else
		ab=$ddd
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi

		#负数转正数 强信号
		((eee=100$bbb))
		((fff=100-$eee))

		#强信号滑动输出
		if [[ "$fff" = "9" ]]; then
		cd=90
		else
		if [[ "$fff" = "8" ]]; then
		cd=9
		else
		if [[ "$fff" = "7" ]]; then
		cd=8
		else
		if [[ "$fff" = "6" ]]; then
		cd=7
		else
		if [[ "$fff" = "5" ]]; then
		cd=6
		else
		if [[ "$fff" = "4" ]]; then
		cd=5
		else
		if [[ "$fff" = "3" ]]; then
		cd=4
		else
		if [[ "$fff" = "2" ]]; then
		cd=3
		else
		if [[ "$fff" = "1" ]]; then
		cd=2
		else
		cd=$fff
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi

		#负数转正数 动态信号
		((ggg=100$rx))
		((hhh=100-$ggg))

		#动态信号滑动输出
		if [[ "$hhh" = "9" ]]; then
		ef=9
		else
		if [[ "$hhh" = "8" ]]; then
		ef=8
		else
		if [[ "$hhh" = "7" ]]; then
		ef=7
		else
		if [[ "$hhh" = "6" ]]; then
		ef=6
		else
		if [[ "$hhh" = "5" ]]; then
		ef=5
		else
		if [[ "$hhh" = "4" ]]; then
		ef=4
		else
		if [[ "$hhh" = "3" ]]; then
		ef=3
		else
		if [[ "$hhh" = "2" ]]; then
		ef=2
		else
		if [[ "$hhh" = "1" ]]; then
		ef=1
		else
		ef=90
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi

		#判断单双数 弱信号
		iii=(`echo "$ddd" | grep '$' | wc -L`)

		#判断单双数 强信号
		jjj=(`echo "$fff" | grep '$' | wc -L`)

		#判断单双数 动态信号
		kkk=(`echo "$hhh" | grep '$' | wc -L`)
		if [[ "$kkk" = "2" ]]; then
		kka=5
		else
		kka=3
		fi

		# 弱信号单双互对 防止数学偏科
		((lll=$iii+$kka))
		#当弱信号阀值为双数动态为单数
		if [[ "$lll" = "5" ]]; then
		# 弱信号滑动输入
		mmm=$ab
		else
		#当弱信号阀值为单数动态为双数
		if [[ "$lll" = "6" ]]; then
		# 动态信号滑动输入
		mmm=$ef
		else
		#当两者皆为单数或双数
		mmm=$hhh
		fi
		fi

		# 强信号单双互对 防止数学偏科
		((nnn=$jjj+$kka))
		#当强信号阀值为双数动态为单数
		if [[ "$nnn" = "5" ]]; then
		# 强信号滑动输入
		ooo=$cd
		else
		#当强信号阀值为单数动态为双数
		if [[ "$nnn" = "6" ]]; then
		# 动态信号滑动输入
		ooo=$ef
		else
		#当两者皆为单数或双数
		ooo=$hhh
		fi
		fi


		#无配置不工作
		if [[ "$aaa" = "0" ]]; then
		bgm=$mmm
		else
		bgm=$ddd
		fi

		#信号强度比较 弱信号剔除
		if [[ "$mmm" > "$bgm" ]]; then
		#端茶送客，人走茶凉！有朋自远方来 吾之送走乎 闭门谢客叁秒 承蒙再临叨扰
		ubus call hostapd.wlanz del_client '{"addr":"'"$mac"'", "reason": 5, "deauth": True, "ban_time": 3000}'
		echo "[ 弱信号 ]$time 启禀主人：wlanz|$mac $rx已经被撵走了呢，么么哒！" >> /var/log/kickass.log

		fi

		#阀值比较 中立不作操作
		if [[ "$consult" = "$strong" ]]; then

		sleep 0

		else
		#无配置不工作
		if [[ "$bbb" = "0" ]]; then
		bgf=$ooo
		else
		bgf=$fff
		fi

		#信号强度比较 强信号剔除
		if [[ "$ooo" < "$bgf" ]]; then
		#端茶送客，人走茶凉！有朋自远方来 吾之送走乎 闭门谢客叁秒 承蒙再临叨扰
		ubus call hostapd.wlanz del_client '{"addr":"'"$mac"'", "reason": 5, "deauth": True, "ban_time": 3000}'
		echo "[ 强信号 ]$time 启禀主人：wlanz|$mac $rx已经被赶跑了呢，么么哒！" >> /var/log/kickass.log

		fi
		fi
	done

	#延时0秒
	sleep 0

	#中断循环
	break;

done
