#!/bin/sh
COT=0
while [ $COT -le 59 ] #执行循环数
do
COT=`expr $COT + 1` #如不被中断总共循环60次

#----------------------------------------创建条件-----------------------------------------

		#i=已运行循环数减1 因为无线是以0开始排序的 减1是为了让初次输出结果为0以对应无线排序
		((i=$COT-1))

		#获取系统时间
		system=(`date +%f`)
		time=${system}

		#获取中断
		if [ -f "/tmp/kickass/stop" ];then
		echo "$time 嗯～ 好累啊，休息会儿！" >> /tmp/log/kickass.log
		#停止运行
		break;
fi

#----------------------------------------无线数量-----------------------------------------

		#用于获取无线网卡数量 原理：通过ifconfig判断无线带有wlan的条目数量
		a=(`ifconfig -a | grep 'wlan' | sort -u | wc -l`)

		#写入首次无线网卡数量信息 防止命令失效
		if [ ! -f "/tmp/kickass/info" ];then
		echo "$a" >> /tmp/kickass/info
fi

		#用于获取无线网卡数量 原理：判断无线配置“wireless”中有几个“ssid”热拔插usb无线网卡易出错
		b=(`cat /etc/config/wireless | grep -c "ssid"`)

		((aa=$a+0))
		((ab=$b+0))

		#用于获取首次无线网卡数量信息
		if [[ "$COT" = "1" ]]; then
		c=$aa
		else
		if [ -f "/tmp/kickass/info" ];then
		c=(`cat /tmp/kickass/info`)
fi
fi

		#用于控制无线网卡数量信息输出
		if [[ "$COT" = "1" ]]; then
		if [[ "$aa" = "0" ]]; then
		out=0
		else
		if [[ "$aa" = "$c" ]]; then
		out=$aa
		else
		if [[ "$aa" > "$c" ]]; then
		out=$aa
		else
		out=$c
fi
fi
fi
		else
		if [[ "$aa" = "$c" ]]; then
		out=$aa
		else
		if [[ "$aa" > "$c" ]]; then
		out=$aa
		else
		out=$c
fi
fi
fi

#----------------------------------------条件报错-----------------------------------------

		if [[ "$COT" = "60" ]]; then
		if [[ "$out" = "0" ]]; then
		echo "$time -----------经过60次检测后---------" >> /var/log/kickass.log
		echo "$time ---------依旧没有发现无线网卡------" >> /var/log/kickass.log
		echo "$time ---------请断电后接入无线网卡------" >> /var/log/kickass.log
		echo "$time 确认过眼神，你是个用不起无线网卡的人！" >> /var/log/kickass.log
		echo "$time -----------脚本已停止运行----------" >> /var/log/kickass.log
fi
fi

#----------------------------------------确认条件-----------------------------------------

		#再三确认条件，用于判断无线条目是否真实存在
		wa=(`ifconfig -a | grep 'wlan0' | sort -u | wc -l`)
		wb=(`ifconfig -a | grep 'wlan1' | sort -u | wc -l`)
		wc=(`ifconfig -a | grep 'wlan2' | sort -u | wc -l`)
		wd=(`ifconfig -a | grep 'wlan3' | sort -u | wc -l`)
		we=(`ifconfig -a | grep 'wlan4' | sort -u | wc -l`)
		wf=(`ifconfig -a | grep 'wlan5' | sort -u | wc -l`)
		wg=(`ifconfig -a | grep 'wlan6' | sort -u | wc -l`)
		wh=(`ifconfig -a | grep 'wlan7' | sort -u | wc -l`)
		wi=(`ifconfig -a | grep 'wlan8' | sort -u | wc -l`)
		wj=(`ifconfig -a | grep 'wlan9' | sort -u | wc -l`)

#----------------------------------------建立脚本-----------------------------------------

		#判断脚本目录是否存在
		if [ ! -d "/tmp/kickass" ];then
		mkdir -p /tmp/kickass/
fi

		#建立用于 wlan$i 的无线剔除脚本
		if [[ "$out" > "0" ]]; then
		if [ ! -f "/tmp/kickass/wlan$i" ];then
		cat /usr/share/kickass/Example | tr "z" "$i" > /tmp/kickass/wlan$i
		echo "$time 建立用于 wlan$i 的无线剔除脚本" >> /var/log/kickass.log
fi
fi

#----------------------------------------任务分发-----------------------------------------

		if [[ "$aa" = "$ab" ]]; then
		if [[ "$wa" = "1" ]]; then
		#判断该脚本文件是否存在
		if [ -f "/tmp/kickass/wlan0" ];then
		bash /tmp/kickass/wlan0
fi
fi
		if [[ "$wb" = "1" ]]; then
		#判断该脚本文件是否存在
		if [ -f "/tmp/kickass/wlan1" ];then
		bash /tmp/kickass/wlan1
fi
fi
		if [[ "$wc" = "1" ]]; then
		#判断该脚本文件是否存在
		if [ -f "/tmp/kickass/wlan2" ];then
		bash /tmp/kickass/wlan2
fi
fi
		if [[ "$wd" = "1" ]]; then
		#判断该脚本文件是否存在
		if [ -f "/tmp/kickass/wlan3" ];then
		bash /tmp/kickass/wlan3
fi
fi
		if [[ "$we" = "1" ]]; then
		#判断该脚本文件是否存在
		if [ -f "/tmp/kickass/wlan4" ];then
		bash /tmp/kickass/wlan4
fi
fi
		if [[ "$wf" = "1" ]]; then
		#判断该脚本文件是否存在
		if [ -f "/tmp/kickass/wlan5" ];then
		bash /tmp/kickass/wlan5
fi
fi
		if [[ "$wg" = "1" ]]; then
		#判断该脚本文件是否存在
		if [ -f "/tmp/kickass/wlan6" ];then
		bash /tmp/kickass/wlan6
fi
fi
		if [[ "$wh" = "1" ]]; then
		#判断该脚本文件是否存在
		if [ -f "/tmp/kickass/wlan7" ];then
		bash /tmp/kickass/wlan7
fi
fi
		if [[ "$wi" = "1" ]]; then
		#判断该脚本文件是否存在
		if [ -f "/tmp/kickass/wlan8" ];then
		bash /tmp/kickass/wlan8
fi
fi
		if [[ "$wj" = "1" ]]; then
		#判断该脚本文件是否存在
		if [ -f "/tmp/kickass/wlan9" ];then
		bash /tmp/kickass/wlan9
fi
fi
fi

#---------------------------------------重执脚本-----------------------------------------
		#回调
		if [[ "$out" = "0" ]]; then
		sleep 0
		else
		if [[ "$COT" = "$out" ]]; then
		exec bash /usr/share/kickass/Main
fi
fi

done
