#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PROG='/usr/sbin/kickass'

service_triggers()
{
	procd_add_reload_trigger 'kickass'
}

start_instance() {
	local cfg="$1"
	config_get_bool enabled "$cfg" 'enabled' '0'
}

start_service() {

	config_load 'kickass'
	config_foreach start_instance 'kickass'

	[ "$enabled" -gt 0 ] || return 1

	procd_open_instance #启动进程实例 进程必须挂在前台
	procd_set_param command $PROG #执行启动命令
	procd_set_param respawn #启用进程守护
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance #关闭进程实例 等同于 CTRL + C
}
