# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for kickass
LUCI_PKGARCH:=all
#需要显示自定义版本请注释掉 反正也是假的(怎么该都行)
#PKG_VERSION:=1.0
#PKG_RELEASE:=1

#include ../../luci.mk
#include ../../main.mk
include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature


